### ISSUE TITLE
4 vulnerabilities found in WpForo 1.6.5 (last version)

### ISSUE THREAD

**Issue by Sh0ckFR** [DediData/wpforo#4]
Hello,

I decided to remove this message for security reasons, you can read the details of the vulnerabilities directly in your mailbox (if you need help, I stay available to help you).

**Comment by gVectors** [comment]
Hi Sh0ckFR,
So, where can can find more information? Have you contacted to plugin developers?

**Comment by Sh0ckFR** [comment]
Hello,

I tried to contact you with your email but I can be contacted on twitter too @Sh0ckFR or email : xena@usa.com (I will ask a proof to be sure that you are the main developer of the project to avoid to release some information to potential attackers)
